openapi: "3.0.0"
info:
  version: 1.0.0
  title: Imbricae Stack API
  license:
    name: MIT

paths:
  /collection/{collection-name}/page/{page-identifier}/content:
    get:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/content/get.yaml"
  /collection/{collection-name}/page/{page-identifier}/metadata:
    get:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/metadata/get.yaml"
  /collections:
    get:
      $ref: "./paths/collections/get.yaml"
components:
  schemas:
    Collection:
      $ref: "./schemas/collection.yaml"
    Page-Snapshot:
      $ref: "./schemas/page-snapshot.yaml"
    Page-Metadata:
      $ref: "./schemas/page-metadata.yaml"
    Error:
      $ref: "./schemas/error.yaml"
