openapi: "3.0.0"
info:
  version: 1.0.0
  title: Imbricae Stack API
  license:
    name: MIT

paths:
  /collection/{collection-name}/page/{page-identifier}:
    delete:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/delete.yaml"
    put:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/put.yaml"
  /collection/{collection-name}/page/{page-identifier}/content:
    get:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/content/get.yaml"
  /collection/{collection-name}/page/{page-identifier}/metadata:
    get:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/metadata/get.yaml"
  /collection/{collection-name}/page/{page-identifier}/retitle:
    post:
      $ref: "./paths/collection/{collection-name}/page/{page-identifier}/retitle/post.yaml"
  /collection/{collection-name}/pages/create:
    post:
      $ref: "./paths/collection/{collection-name}/pages/create/post.yaml"
  /collection/{collection-name}/pages/query:
    post:
      $ref: "./paths/collection/{collection-name}/pages/query/post.yaml"
  /collection/{collection-name}/pages/search:
    post:
      $ref: "./paths/collection/{collection-name}/pages/search/post.yaml"
  /collections:
    get:
      $ref: "./paths/collections/get.yaml"
  /script/{script-identifier}/script:
    get:
      $ref: "./paths/script/{script-identifier}/script/get.yaml"
  /scripts/create:
    post:
      $ref: "./paths/scripts/create/post.yaml"
  /scripts/query:
    post:
      $ref: "./paths/scripts/query/post.yaml"
  /scripts/search:
    post:
      $ref: "./paths/scripts/search/post.yaml"
components:
  schemas:
    Collection:
      $ref: "./schemas/collection.yaml"
    Page-Snapshot:
      $ref: "./schemas/page-snapshot.yaml"
    Page-Metadata:
      $ref: "./schemas/page-metadata.yaml"
    Error:
      $ref: "./schemas/error.yaml"
